### PR TITLE
Update rbenv submodule to latest version

### PR DESCRIPTION
**Pull request by bycEEE**

### CODE REVIEW

**Comment by dannyfinks** [comment]
Thank you @bycEEE - we're actually utilizing this for our automated tests on the player team

**Comment by asobrien** [comment]
LGTM!

**Comment by dannyfinks** [comment]
@bycEEE not sure if it matters to you, but if you did want to add a new ruby version to provisioning as a follow to this it can be done like so - https://github.com/jwplayer/provisioning/pull/2476/commits/f480cda144f1ecb760bb31f87362725db2e53296

**Comment by bycEEE** [comment]
@dannyfinks that helps, thanks!

**Pull request merged**
